cmd_arch/arm64/boot/dts/exynos/exynos9630.dtb := mkdir -p arch/arm64/boot/dts/exynos/ ; ./bin/clang -E -Wp,-MD,arch/arm64/boot/dts/exynos/.exynos9630.dtb.d.pre.tmp -nostdinc -I./scripts/dtc/include-prefixes -undef -D__DTS__ -DANDROID_VERSION=130000 -DANDROID_MAJOR_VERSION=t -x assembler-with-cpp -o arch/arm64/boot/dts/exynos/.exynos9630.dtb.dts.tmp arch/arm64/boot/dts/exynos/exynos9630.dts ; ./scripts/dtc/dtc -O dtb -o arch/arm64/boot/dts/exynos/exynos9630.dtb -b 0 -a 4 -iarch/arm64/boot/dts/exynos/ -i./scripts/dtc/include-prefixes -@ -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-pci_device_reg -Wno-sound_dai_property -Wno-gpios_property -Wno-interrupts_property -Wno-clocks_property -Wno-io_channels_property -Wno-avoid_default_addr_size -Wno-reg_format -Wno-dmas_property  -d arch/arm64/boot/dts/exynos/.exynos9630.dtb.d.dtc.tmp arch/arm64/boot/dts/exynos/.exynos9630.dtb.dts.tmp 2>arch/arm64/boot/dts/exynos/exynos9630.dtb.dtout || ( cat  arch/arm64/boot/dts/exynos/exynos9630.dtb.dtout; for err in "$$(cat  arch/arm64/boot/dts/exynos/exynos9630.dtb.dtout | grep 'Error:')"; do echo "See more detail error as below:"; cat $$(echo $$err | cut -d':' -f2) | awk '{printf("ERROR: %6d  %s\n"), NR, $$0}' | head -n $$(echo $$err | grep -Eo ':[0-9]+' | cut -d':' -f2) | tail -n 2; done; rm  arch/arm64/boot/dts/exynos/exynos9630.dtb.dtout; false; ) ; ./scripts/dtc/dtc -O dts -I dtb -o arch/arm64/boot/dts/exynos/exynos9630.dtb.reverse.dts -@ -Wno-unit_address_vs_reg -Wno-unit_address_format -Wno-avoid_unnecessary_addr_size -Wno-alias_paths -Wno-graph_child_address -Wno-graph_port -Wno-unique_unit_address -Wno-pci_device_reg -Wno-sound_dai_property -Wno-gpios_property -Wno-interrupts_property -Wno-clocks_property -Wno-io_channels_property -Wno-avoid_default_addr_size -Wno-reg_format -Wno-dmas_property  arch/arm64/boot/dts/exynos/exynos9630.dtb ; cat arch/arm64/boot/dts/exynos/.exynos9630.dtb.d.pre.tmp arch/arm64/boot/dts/exynos/.exynos9630.dtb.d.dtc.tmp > arch/arm64/boot/dts/exynos/.exynos9630.dtb.d

source_arch/arm64/boot/dts/exynos/exynos9630.dtb := arch/arm64/boot/dts/exynos/exynos9630.dts

deps_arch/arm64/boot/dts/exynos/exynos9630.dtb := \

arch/arm64/boot/dts/exynos/exynos9630.dtb: $(deps_arch/arm64/boot/dts/exynos/exynos9630.dtb)

$(deps_arch/arm64/boot/dts/exynos/exynos9630.dtb):
