name: Samsung Galaxy A51 5G Kernel Build

on:
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        mode: [ksun, apatch]
    steps:
    - name: Import Kernel Source
      uses: actions/checkout@v4   
      
    - name: Install Required Package
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential make automake autoconf libtool pkg-config \
          bc bison flex libssl-dev libelf-dev libncurses5-dev libncurses-dev cpio \
          clang lld gcc g++ \
          git curl rsync wget pv \
          python3 python3-pip python-is-python3 \
          openjdk-17-jdk \
          zip unzip p7zip-full tar \
          lz4 xz-utils zlib1g-dev uuid-dev \
          erofs-utils android-sdk-libsparse-utils \
          fuse3 libfuse3-dev f2fs-tools fuse2fs attr e2fsprogs \
          kmod
        wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb && sudo dpkg -i libtinfo5_6.3-2ubuntu0.1_amd64.deb  


    - name: Setting Scripts Permission
      run: |    
        chmod +x build.sh
        chmod +x prebuilts/*         

    - name: Kernel Build
      run: |   
        ./build.sh ${{ matrix.mode }}

    - name: Upload Artifacts Kernel File
      uses: actions/upload-artifact@v4
      with:
        name: "A51_Kernel_${{ matrix.mode }}_File"
        path: |
          ./prebuilts/output/*